<option value="Worldwide">@lang('Worldwide')</option>
<option value="Afghanistan">@lang('Afghanistan')</option>
<option value="Albania">@lang('Albania')</option>
<option value="Algeria">@lang('Algeria')</option>
<option value="Andorra">@lang('Andorra')</option>
<option value="Angola">@lang('Angola')</option>
<option value="Anguilla">@lang('Anguilla')</option>
<option value="Antarctica">@lang('Antarctica')</option>
<option value="Antigua and Barbuda">@lang('Antigua and Barbuda')</option>
<option value="Argentina">@lang('Argentina')</option>
<option value="Armenia">@lang('Armenia')</option>
<option value="Aruba">@lang('Aruba')</option>
<option value="Australia">@lang('Australia')</option>
<option value="Austria">@lang('Austria')</option>
<option value="Azerbaijan">@lang('Azerbaijan')</option>
<option value="Bahamas">@lang('Bahamas')</option>
<option value="Bahrain">@lang('Bahrain')</option>
<option value="Bangladesh">@lang('Bangladesh')</option>
<option value="Barbados">@lang('Barbados')</option>
<option value="Belarus">@lang('Belarus')</option>
<option value="Belgium">@lang('Belgium')</option>
<option value="Belize">@lang('Belize')</option>
<option value="Benin">@lang('Benin')</option>
<option value="Bermuda">@lang('Bermuda')</option>
<option value="Bhutan">@lang('Bhutan')</option>
<option value="Bolivia">@lang('Bolivia')</option>
<option value="Bosnia and Herzegovina">@lang('Bosnia and Herzegovina')</option>
<option value="Botswana">@lang('Botswana')</option>
<option value="Bouvet Island">@lang('Bouvet Island')</option>
<option value="Brazil">@lang('Brazil')</option>
<option value="Brunei Darussalam">@lang('Brunei Darussalam')</option>
<option value="Bulgaria">@lang('Bulgaria')</option>
<option value="Burkina Faso">@lang('Burkina Faso')</option>
<option value="Burundi">@lang('Burundi')</option>
<option value="Cambodia">@lang('Cambodia')</option>
<option value="Cameroon">@lang('Cameroon')</option>
<option value="Canada">@lang('Canada')</option>
<option value="Chad">@lang('Chad')</option>
<option value="Chile">@lang('Chile')</option>
<option value="China">@lang('China')</option>
<option value="Colombia">@lang('Colombia')</option>
<option value="Comoros">@lang('Comoros')</option>
<option value="Congo">@lang('Congo')</option>
<option value="Costa Rica">@lang('Costa Rica')</option>
<option value="Cote d'Ivoire">@lang("Cote d'Ivoire")</option>
<option value="Croatia">@lang('Croatia')</option>
<option value="Cuba">@lang('Cuba')</option>
<option value="Cyprus">@lang('Cyprus')</option>
<option value="Czech Republic">@lang('Czech Republic')</option>
<option value="Denmark">@lang('Denmark')</option>
<option value="Djibouti">@lang('Djibouti')</option>
<option value="Dominica">@lang('Dominica')</option>
<option value="Dominican Republic">@lang('Dominican Republic')</option>
<option value="Ecuador">@lang('Ecuador')</option>
<option value="Egypt">@lang('Egypt')</option>
<option value="El Salvador">@lang('El Salvador')</option>
<option value="Equatorial Guinea">@lang('Equatorial Guinea')</option>
<option value="Eritrea">@lang('Eritrea')</option>
<option value="Estonia">@lang('Estonia')</option>
<option value="Ethiopia">@lang('Ethiopia')</option>
<option value="Fiji">@lang('Fiji')</option>
<option value="Finland">@lang('Finland')</option>
<option value="France">@lang('France')</option>
<option value="Gabon">@lang('Gabon')</option>
<option value="Gambia">@lang('Gambia')</option>
<option value="Georgia">@lang('Georgia')</option>
<option value="Germany">@lang('Germany')</option>
<option value="Ghana">@lang('Ghana')</option>
<option value="Gibraltar">@lang('Gibraltar')</option>
<option value="Greece">@lang('Greece')</option>
<option value="Greenland">@lang('Greenland')</option>
<option value="Grenada">@lang('Grenada')</option>
<option value="Guadeloupe">@lang('Guadeloupe')</option>
<option value="Guam">@lang('Guam')</option>
<option value="Guatemala">@lang('Guatemala')</option>
<option value="Guernsey">@lang('Guernsey')</option>
<option value="Guinea">@lang('Guinea')</option>
<option value="Guinea-Bissau">@lang('Guinea-Bissau')</option>
<option value="Guyana">@lang('Guyana')</option>
<option value="Haiti">@lang('Haiti')</option>
<option value="Honduras">@lang('Honduras')</option>
<option value="Hong Kong">@lang('Hong Kong')</option>
<option value="Hungary">@lang('Hungary')</option>
<option value="Iceland">@lang('Iceland')</option>
<option value="India">@lang('India')</option>
<option value="Indonesia">@lang('Indonesia')</option>
<option value="Iran">@lang('Iran')</option>
<option value="Iraq">@lang('Iraq')</option>
<option value="Ireland">@lang('Ireland')</option>
<option value="Isle of Man">@lang('Isle of Man')</option>
<option value="Israel">@lang('Israel')</option>
<option value="Italy">@lang('Italy')</option>
<option value="Jamaica">@lang('Jamaica')</option>
<option value="Japan">@lang('Japan')</option>
<option value="Jersey">@lang('Jersey')</option>
<option value="Jordan">@lang('Jordan')</option>
<option value="Kazakhstan">@lang('Kazakhstan')</option>
<option value="Kenya">@lang('Kenya')</option>
<option value="Kiribati">@lang('Kiribati')</option>
<option value="Kosovo">@lang('Kosovo')</option>
<option value="Kuwait">@lang('Kuwait')</option>
<option value="Kyrgyzstan">@lang('Kyrgyzstan')</option>
<option value="Laos">@lang('Laos')</option>
<option value="Latvia">@lang('Latvia')</option>
<option value="Lebanon">@lang('Lebanon')</option>
<option value="Lesotho">@lang('Lesotho')</option>
<option value="Liberia">@lang('Liberia')</option>
<option value="Liechtenstein">@lang('Liechtenstein')</option>
<option value="Lithuania">@lang('Lithuania')</option>
<option value="Luxembourg">@lang('Luxembourg')</option>
<option value="Macao">@lang('Macao')</option>
<option value="Macedonia">@lang('Macedonia')</option>
<option value="Madagascar">@lang('Madagascar')</option>
<option value="Malawi">@lang('Malawi')</option>
<option value="Malaysia">@lang('Malaysia')</option>
<option value="Maldives">@lang('Maldives')</option>
<option value="Mali">@lang('Mali')</option>
<option value="Malta">@lang('Malta')</option>
<option value="Martinique">@lang('Martinique')</option>
<option value="Mauritania">@lang('Mauritania')</option>
<option value="Mauritius">@lang('Mauritius')</option>
<option value="Mayotte">@lang('Mayotte')</option>
<option value="Mexico">@lang('Mexico')</option>
<option value="Moldova">@lang('Moldova')</option>
<option value="Monaco">@lang('Monaco')</option>
<option value="Mongolia">@lang('Mongolia')</option>
<option value="Montenegro">@lang('Montenegro')</option>
<option value="Montserrat">@lang('Montserrat')</option>
<option value="Morocco">@lang('Morocco')</option>
<option value="Mozambique">@lang('Mozambique')</option>
<option value="Myanmar">@lang('Myanmar')</option>
<option value="Namibia">@lang('Namibia')</option>
<option value="Nauru">@lang('Nauru')</option>
<option value="Nepal">@lang('Nepal')</option>
<option value="Netherlands">@lang('Netherlands')</option>
<option value="New Caledonia">@lang('New Caledonia')</option>
<option value="New Zealand">@lang('New Zealand')</option>
<option value="Nicaragua">@lang('Nicaragua')</option>
<option value="Niger">@lang('Niger')</option>
<option value="Nigeria">@lang('Nigeria')</option>
<option value="Norway">@lang('Norway')</option>
<option value="Oman">@lang('Oman')</option>
<option value="Pakistan">@lang('Pakistan')</option>
<option value="Palau">@lang('Palau')</option>
<option value="Panama">@lang('Panama')</option>
<option value="Papua New Guinea">@lang('Papua New Guinea')</option>
<option value="Paraguay">@lang('Paraguay')</option>
<option value="Peru">@lang('Peru')</option>
<option value="Philippines">@lang('Philippines')</option>
<option value="Pitcairn">@lang('Pitcairn')</option>
<option value="Poland">@lang('Poland')</option>
<option value="Portugal">@lang('Portugal')</option>
<option value="Puerto Rico">@lang('Puerto Rico')</option>
<option value="Qatar">@lang('Qatar')</option>
<option value="Romania">@lang('Romania')</option>
<option value="Russia">@lang('Russia')</option>
<option value="Rwanda">@lang('Rwanda')</option>
<option value="Saudi Arabia">@lang('Saudi Arabia')</option>
<option value="Senegal">@lang('Senegal')</option>
<option value="Serbia">@lang('Serbia')</option>
<option value="Seychelles">@lang('Seychelles')</option>
<option value="Sierra Leone">@lang('Sierra Leone')</option>
<option value="Singapore">@lang('Singapore')</option>
<option value="Slovakia">@lang('Slovakia')</option>
<option value="Slovenia">@lang('Slovenia')</option>
<option value="Somalia">@lang('Somalia')</option>
<option value="South Africa">@lang('South Africa')</option>
<option value="South Korea">@lang('South Korea')</option>
<option value="South Sudan">@lang('South Sudan')</option>
<option value="Spain">@lang('Spain')</option>
<option value="Sri Lanka">@lang('Sri Lanka')</option>
<option value="Sudan">@lang('Sudan')</option>
<option value="Swaziland">@lang('Swaziland')</option>
<option value="Sweden">@lang('Sweden')</option>
<option value="Switzerland">@lang('Switzerland')</option>
<option value="Syrian Arab Republic">@lang('Syrian Arab Republic')</option>
<option value="Taiwan">@lang('Taiwan')</option>
<option value="Tajikistan">@lang('Tajikistan')</option>
<option value="Tanzania">@lang('Tanzania, United Republic of Tanzania')</option>
<option value="Thailand">@lang('Thailand')</option>
<option value="Timor-Leste">@lang('Timor-Leste')</option>
<option value="Togo">@lang('Togo')</option>
<option value="Tokelau">@lang('Tokelau')</option>
<option value="Tonga">@lang('Tonga')</option>
<option value="Trinidad and Tobago">@lang('Trinidad and Tobago')</option>
<option value="Tunisia">@lang('Tunisia')</option>
<option value="Turkey">@lang('Turkey')</option>
<option value="Turkmenistan">@lang('Turkmenistan')</option>
<option value="Tuvalu">@lang('Tuvalu')</option>
<option value="Uganda">@lang('Uganda')</option>
<option value="Ukraine">@lang('Ukraine')</option>
<option value="United Arab Emirates">@lang('United Arab Emirates')</option>
<option value="United Kingdom">@lang('United Kingdom')</option>
<option value="United States">@lang('United States')</option>
<option value="Uruguay">@lang('Uruguay')</option>
<option value="Uzbekistan">@lang('Uzbekistan')</option>
<option value="Vanuatu">@lang('Vanuatu')</option>
<option value="Venezuela">@lang('Venezuela, Bolivarian Republic of Venezuela')</option>
<option value="Vietnam">@lang('Vietnam')</option>
<option value="Yemen">@lang('Yemen')</option>
<option value="Zambia">@lang('Zambia')</option>
<option value="Zimbabwe">@lang('Zimbabwe')</option>
