@extends($activeTemplate . 'layouts.master')
@section('content')
    <div class="row justify-content-center">
        <h5 class="form-label font-weight-bold mb-4 text-center"><strong>@lang('Two-factor Authentication')</strong></h5>
        <hr>
        @if (!auth()->user()->ts)
            <div class="col-md-6 mb-md-0 mb-4">
                <div class="card custom--card">
                    <div class="card-header">
                        <h5 class="m-0">@lang('1. Set up authentication')</h5>
                    </div>

                    <div class="card-body">
                        <h6 class="mb-5">
                            @lang('To begin, please scan the QR code below with your authenticator application')
                        </h6>
                        <div class="form-group mx-auto text-center">
                            <img class="mx-auto" src="{{ $qrCodeUrl }}">
                        </div>

                        <div class="form-group">
                            <label class="form--label">@lang('Setup Key')</label>
                            <div class="input-group">
                                <input class="form-control form--control referralURL" name="key" type="text" value="{{ $secret }}" readonly>
                                <button class="input-group-text copytext" id="copyBoard" type="button"> <i class="fa fa-copy"></i> </button>
                            </div>
                        </div>

                        <label><i class="fa fa-info-circle py-4"></i> @lang('Help')</label>
                        <p>@lang('We recommend using Google Authenticator available for both') <a class="text--base"
                                href="https://apps.apple.com/us/app/google-authenticator/id388497605"
                                target="_blank">@lang('iPhone')</a>>@lang(' and ')<a class="text--base"
                                href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en"
                                target="_blank">@lang('Android')</a>@lang(' phones. ')</p>
                    </div>
                </div>
            </div>
        @endif

        <div class="col-md-6">

            @if (auth()->user()->ts)
                <div class="card custom--card">
                    <div class="card-header">
                        <h5 class="m-0">@lang('Disable 2FA Security')</h5>
                    </div>
                    <div class="card-body">
                        <form class="dashboard-form" action="{{ route('user.twofactor.disable') }}" method="POST">
                            @csrf
                            <input name="key" type="hidden" value="{{ $secret }}">
                            <div class="form-group">
                                <label class="form--label">@lang('Google Authenticatior OTP')</label>
                                <input class="form--control" name="code" type="text" required>
                            </div>
                            <button class="btn btn--base w-100" type="submit">@lang('Submit')</button>

                        </form>
                    </div>
                </div>
            @else
                <div class="card custom--card">
                    <div class="card-header">
                        <h5 class="m-0">@lang('2. Validate')</h5>
                    </div>
                    <form class="dashboard-form" action="{{ route('user.twofactor.enable') }}" method="POST">
                        <div class="card-body">
                            @csrf
                            <input name="key" type="hidden" value="{{ $secret }}">
                            <div class="form-group">
                                <label class="form--label">@lang('Google Authenticatior OTP')</label>
                                <input class="form--control" name="code" type="text" required>
                            </div>
                            <button class="btn btn--base w-100" type="submit">@lang('Enable')</button>
                            <label><i class="fa fa-info-circle py-4"></i> @lang('Help')</label>
                        <p>@lang('To verify your successful configuration, please enter the code generated by your authentication application below.')</p>
                        </div>
                    </form>
                </div>
            @endif
        </div>
    </div>
@endsection

@push('style')
    <style>
        .copied::after {
            background-color: #{{ gs('base_color') }};
        }
    </style>
@endpush

@push('script')
    <script>
        (function($) {
            "use strict";
            $('#copyBoard').on("click", function() {
                var copyText = document.getElementsByClassName("referralURL");
                copyText = copyText[0];
                copyText.select();
                copyText.setSelectionRange(0, 99999);
                /*For mobile devices*/
                document.execCommand("copy");
                copyText.blur();
                this.classList.add('copied');
                setTimeout(() => this.classList.remove('copied'), 1500);
            });
        })(jQuery);
    </script>
@endpush
